inputs:
  type: dict
  required: true
  schema:
    profile_directory:
      # Directory to load the profile YAML from.
      type: string
      required: true
outputs:
  type: dict
  required: true
  schema:
    profile_yaml:
      type: dict
      required: true
      schema:
        censored:
          # File name to save the censored profile YAML.
          type: string
          required: true
        uncensored:
          # File name to save the uncensored profile YAML.
          type: string
          required: true
    cv:
      type: dict
      required: true
      schema:
        censored:
          # File name to save the censored CV PDF.
          type: string
          required: true
        uncensored:
          # File name to save the uncensored CV PDF.
          type: string
          required: true
        exclude:
          # List of 'experience' keys to exclude from CV output.
          type: list
          required: true
    website:
      type: dict
      required: true
      schema:
        directory:
          # The directory to save the website output in.
          type: string
          required: true
        background:
          # Alternative image background to use for website.
          type: string
          nullable: true
        favicon:
          # Alternative image background to use for website.
          type: string
          nullable: true