inputs:
  profile_directory: profile
outputs:
  profile_yaml:
    censored: output/profile-public.yml
    uncensored: output/profile-private.yml
  cv:
    censored: output/cv_public.pdf
    uncensored: output/cv_private.pdf
    exclude: []
  website:
    directory: output/website
    background: null